
const DATA = window.GNG_POKEDEX_DATA || [];
const state = { map: "全部地图", q: "", current: null };
const $ = (s) => document.querySelector(s);
const grid = $("#grid"), detail = $("#detail"), home = $("#home"), count = $("#count"), mapFilter = $("#mapFilter"), search = $("#search");
function esc(s){return String(s ?? "").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));}
function maps(){return ["全部地图", ...Array.from(new Set(DATA.map(x=>x.map).filter(Boolean)))];}
function filtered(){const q=state.q.trim().toLowerCase();return DATA.filter(x=>(state.map==="全部地图"||x.map===state.map)&&(!q||[x.name,x.foodId,x.map,...x.monsters.map(m=>m.name)].join(" ").toLowerCase().includes(q)));}
function renderHome(){const rows=filtered();count.textContent=`${rows.length}/${DATA.length}`;grid.innerHTML=rows.map(x=>`<article class="card"><button type="button" onclick="openItem('${esc(x.foodId)}')"><div class="thumb"><img src="${esc(x.foodIcon||x.comic)}" alt="${esc(x.name)}"></div><div class="card-body"><div class="dex"><span>No.${String(x.index).padStart(3,"0")}</span><span>${esc(x.foodId)}</span></div><div class="name">${esc(x.name)}</div><span class="map">${esc(x.map)}</span></div></button></article>`).join("");}
function openItem(id){const item=DATA.find(x=>x.foodId===id);if(!item)return;state.current=id;home.style.display="none";detail.classList.add("active");$("#comic").src=item.comic;$("#comic").alt=item.name;$("#title").textContent=item.name;$("#meta").innerHTML=`<b>食材ID</b><span>${esc(item.foodId)}</span><b>地图</b><span>${esc(item.map)}</span><b>来源关系</b><span>${esc(item.relationship||"")}</span><b>选择版本</b><span>#${String(item.variant).padStart(2,"0")}</span>`;$("#desc").textContent=item.description||"Wiki 当前源未填写描述。";$("#monsters").innerHTML=item.monsters.map(m=>`<div class="monster">${m.image?`<img src="${esc(m.image)}" alt="${esc(m.name)}">`:`<div></div>`}<div><div class="mname">${esc(m.name)}</div><div class="mrel">${esc(m.difficulty||"")} ${esc(m.relationship||"")}</div></div></div>`).join("");$("#promptText").textContent=item.prompt||"未找到该候选图的生成提示词。";location.hash=`item-${id}`;window.scrollTo({top:0,behavior:"smooth"});}
function closeItem(){state.current=null;detail.classList.remove("active");home.style.display="block";if(location.hash) history.pushState("",document.title,location.pathname);renderHome();}
function openZoom(){const item=DATA.find(x=>x.foodId===state.current);if(!item)return;$("#zoomImg").src=item.comic;$("#zoomImg").alt=item.name;$("#lightbox").classList.add("active");}
function closeZoom(){$("#lightbox").classList.remove("active");$("#zoomImg").removeAttribute("src");}
function setup(){maps().forEach(m=>{const o=document.createElement("option");o.value=m;o.textContent=m;mapFilter.appendChild(o);});mapFilter.onchange=()=>{state.map=mapFilter.value;renderHome();};search.oninput=()=>{state.q=search.value;renderHome();};$("#back").onclick=closeItem;$("#comic").onclick=openZoom;$("#lightbox").onclick=closeZoom;$("#closeZoom").onclick=closeZoom;document.addEventListener("keydown",e=>{if(e.key==="Escape") closeZoom();});const hash=decodeURIComponent(location.hash||"");renderHome();if(hash.startsWith("#item-")) openItem(hash.replace("#item-",""));}
window.openItem=openItem;setup();
